#!/bin/bash

#Instalação do Void Linux (CHROOT)

#Instalar o xbps-install
wget https://github.com/pscabral/void/blob/master/xbps-0.53-1-x86_64.pkg.tar.xz
pacman -U --noconfirm ./xbps-0.53-1-x86_64.pkg.tar.xz

#Entrada no root.
sudo su

#Particionamento
mkfs.ext4 /dev/sda1
mkfs.ext4 /dev/sda3
mkswap /dev/sda2

#Montagem
swapon /dev/sda2
mount /dev/sda1 /mnt

mkdir /mnt/home
mount /dev/sda3 /mnt/home
cd /mnt

#Download do tarball
wget https://a-hel-fi.m.voidlinux.org/live/20190526/void-x86_64-ROOTFS-20190526.tar.xz
#wget http://ftp4.se.freebsd.org/pub/voidlinux/live/20190526/void-x86_64-ROOTFS-20190526.tar.xz
#wget http://dk.archive.ubuntu.com/voidlinux/live/20190526/void-x86_64-musl-ROOTFS-20190526.tar.xz
#wget http://achieversz.com.mirror.yandex.ru/mirrors/voidlinux/live/20190526/void-x86_64-ROOTFS-20190526.tar.xz
tar xpf void-x86_64-ROOTFS-20190526.tar.xz --xattrs-include='*.*' --numeric-owner
cp /etc/resolv.conf etc/resolv.conf

# repositorios
mkdir -p /mnt/etc/xbps.d ; echo -e 'repository=https://mirrors.dotsrc.org/voidlinux/current/ \nrepository=https://alpha.de.repo.voidlinux.org/current' | tee /mnt/etc/xbps.d/00-repository-main.conf
echo -e 'repository=https://mirrors.dotsrc.org/voidlinux/current/nonfree \nrepository=https://alpha.de.repo.voidlinux.org/current/nonfree' | tee /mnt/etc/xbps.d/00-repository-main.conf/10-repository-nonfree.conf
 
#Arquivo nano /usr/share/xbps.d/00-repository-main.conf
# > repository=https://mirrors.servercentral.com/voidlinux/current
#repository=https://alpha.us.repo.voidlinux.org/current
#repository=http://https//mirror.clarkson.edu/voidlinux/current
#repository=https://alpha.de.repo.voidlinux.org/current
#repository=https://void.webconverger.org/current

#Arquivo nano /usr/share/xbps.d/10-repository-nonfree.conf
# > repository=https://mirrors.servercentral.com/voidlinux/current/nonfree
#repository=https://alpha.us.repo.voidlinux.org/current/nonfree
#repository=http://https//mirror.clarkson.edu/voidlinux/current/nonfree
#repository=https://alpha.de.repo.voidlinux.org/current/nonfree
#repository=https://void.webconverger.org/current/nonfree
 
#Ajustes e entrada no chroot.
# mount --types proc /proc /mnt/void/proc
# mount --rbind /sys /mnt/void/sys
# mount --rbind /dev /mnt/void/dev
# mount --make-rslave /mnt/void/sys
# mount --make-rslave /mnt/void/dev

# gerar o fstab
genfstab -p /mnt >> /mnt/etc/fstab

# entrar em chroot
arch-chroot /mnt /bin/bash

#Atualização dos pacotes.
xbps-install -Su
xbps-install -Suv
xbps-install -Sy nano

#FSTAB.
nano /etc/fstab

#hostname, linguagem ...
echo voidOS > /etc/hostname
nano /etc/hostname
#voidOS

nano /etc/hosts
#127.0.0.1 localhost.localdomain localhost
#::1   localhost.localdomain localhost

nano/etc/rc.conf
echo HOSTNAME="archOs" / HARDWARECLOCK="UTC" / TIMEZONE="America/Sao_Paulo" / KEYMAP="br-abnt2" / FONT="Lat2-Terminus16"" | sed -E 's| / |\n|g' > /etc/rc.conf
nano/etc/rc.conf
#HOSTNAME="voidOS"
#HARDWARECLOCK="localtime"
#TIMEZONE="America/Sao_Paulo"
#KEYMAP="br-abnt2"
#FONT="Lat2-Terminus16"


echo LANG=pt_BR.UTF-8 / LC_COLLATE=C | sed -E 's| / |\n|g' > /etc/locale.conf
nano /etc/locale.conf
#LANG=pt_BR.UTF-8
#LC_COLLATE=C


echo > pt_BR.UTF-8 UTF-8 /etc/default/libc-locales
nano /etc/default/libc-locales
#pt_BR.UTF-8 UTF-8
xbps-reconfigure -f glibc-locales

# Kernel, base-devel e grub.
# xbps-install -S linux linux-headers base-devel
xbps-install -S linux5.2 linux5.2-headers base-devel grub

xbps-install -S grub
grub-install /dev/sda
grub-mkconfig -o /boot/grub/grub.cfg

# Xorg mínimo.
xbps-install -Sy xf86-video-ati xorg-input-drivers xorg-minimal xorg-fonts bash-completion

# Usuários e senhas.
passwd root
useradd -m -s /bin/bash -U -G wheel,users,audio,video,cdrom,input,network pscabral
passwd pscabral

# repo non-free e atualiza
xbps-install -Sy ca-certificates void-repo-nonfree ; xbps-install -Suy

# XFCE4
xbps-install -Sy xfce4-panel xfce4-session xfce4-settings xfconf xfdesktop xfwm4 xfwm4-themes xfce4-terminal exo xfce4-notifyd xfce4-screensaver xdg-user-dirs-gtk upower xfce4-clipman-plugin xfce4-appfinder xfce4-pulseaudio-plugin xfce4-whiskermenu-plugin xfce4-power-manager tumbler ristretto gtk-engine-murrine gdk-pixbuf pulseaudio pavucontrol plank qt5-styleplugins qt5ct

# pacotes basicos
xbps-install -Sy udiskie ntfs-3g alsa-utils xkill wget git dhcpcd dbus cgmanager rsync xdg-user-dirs xdg-utils glibc-locales curl nano dejavu-fonts-ttf polkit NetworkManager network-manager-applet wmctrl xz ConsoleKit2 make cronie setxkbmap gvfs gvfs-smb gvfs-cdda leafpad unrar zip p7zip unzip bzip ffmpeg gst-plugins-bad1 gst-plugins-good1 gst-plugins-ugly1 gst-plugins-base1 vlc lxdm firefox firefox-i18n-pt-BR chromium

#Serviços.
ln -sv /etc/sv/dbus /var/service/
ln -sv /etc/sv/polkitd /var/service/
ln -sv /etc/sv/dhcpcd /var/service/
ln -s /etc/sv/NetworkManager /var/service
ln -sv /etc/sv/consolekit /var/service/
ln -sv /etc/sv/cgmanager /var/service/
ln -sv /etc/sv/lxdm /var/service/











