#!/bin/bash

# Instalando o Void pelo Live do Arch Bang

# instalar o xbps depois de ter executado todos os passos do readme.md
pacman -U --noconfirm ./xbps-0.53-1-x86_64.pkg.tar.xz

# baixar a base-system
echo "Y" | xbps-install -S -R https://mirrors.dotsrc.org/voidlinux/current/ -r /mnt/ base-system

# copiar resolv.conf
cd /etc/resolv.conf /mnt/etc

# repositorios
mkdir -p /mnt/etc/xbps.d ; echo -e 'repository=https://mirrors.dotsrc.org/voidlinux/current/ \nrepository=https://alpha.de.repo.voidlinux.org/current' | tee /mnt/etc/xbps.d/00-repository-main.conf
echo -e 'repository=https://mirrors.dotsrc.org/voidlinux/current/nonfree \nrepository=https://alpha.de.repo.voidlinux.org/current/nonfree' | tee /mnt/etc/xbps.d/00-repository-main.conf/10-repository-nonfree.conf

# gerar o fstab
genfstab -p /mnt >> /mnt/etc/fstab

# entrar em chroot
#arch-chroot /mnt /bin/bash

# entrar em chroot executando o script
cp ./install /mnt ; arch-chroot /mnt 

# gerar o resolv
echo 8.8.8.8 > /etc/resolv.conf
echo 8.8.4.4 > /etc/resolv.conf

sh install
